export const ENGINE_VERSION = "engine-v3-deterministic";
export const FEATURE_VERSION = "features-v2";
export const PROMPT_VERSION = "signal-explanation-v2";

export const FAILURE_CODES = {
  PROVIDER_TIMEOUT: "PROVIDER_TIMEOUT",
  PROVIDER_RATE_LIMIT: "PROVIDER_RATE_LIMIT",
  PROVIDER_SCHEMA_ERROR: "PROVIDER_SCHEMA_ERROR",
  FEATURE_PIPELINE_ERROR: "FEATURE_PIPELINE_ERROR",
  SCORING_ERROR: "SCORING_ERROR",
  PERSISTENCE_ERROR: "PERSISTENCE_ERROR",
  ALERT_DELIVERY_ERROR: "ALERT_DELIVERY_ERROR",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
} as const;

export type FailureCode = typeof FAILURE_CODES[keyof typeof FAILURE_CODES];
